#!/bin/sh
# wal-set.sh — set wallpaper and generate color scheme with pywal16
# Usage: wal-set.sh <path-to-wallpaper>

if [ -z "$1" ]; then
    echo "Usage: wal-set.sh <path-to-wallpaper>"
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "Error: file '$1' not found"
    exit 1
fi

# Generate color scheme (skip setting wallpaper, we use feh)
wal -i "$1" -n

# Set wallpaper with feh
feh --bg-fill "$1"

# ─── Generate neovim base16 theme-colors.lua ───────────────────────
COLORS_JSON="$HOME/.cache/wal/colors.json"
NVIM_THEME="$HOME/.config/nvim/lua/theme-colors.lua"

if [ -f "$COLORS_JSON" ]; then
    # Read pywal colors from JSON
    color0=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color0'])")
    color1=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color1'])")
    color2=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color2'])")
    color3=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color3'])")
    color4=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color4'])")
    color5=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color5'])")
    color6=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color6'])")
    color7=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color7'])")
    color8=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color8'])")
    color9=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color9'])")
    color10=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color10'])")
    color11=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color11'])")
    color12=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color12'])")
    color13=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color13'])")
    color14=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color14'])")
    color15=$(cat "$COLORS_JSON" | python3 -c "import sys,json;print(json.load(sys.stdin)['colors']['color15'])")

    # Map pywal 16 colors to base16 scheme
    # base00 = background, base05 = foreground, base08-0F = accent colors
    mkdir -p "$(dirname "$NVIM_THEME")"
    cat > "$NVIM_THEME" << EOF
-- Auto-generated by wal-set.sh - DO NOT EDIT
return {
  base16 = {
    base00 = "$color0",
    base01 = "$color8",
    base02 = "$color8",
    base03 = "$color3",
    base04 = "$color4",
    base05 = "$color7",
    base06 = "$color15",
    base07 = "$color15",
    base08 = "$color1",
    base09 = "$color9",
    base0A = "$color3",
    base0B = "$color2",
    base0C = "$color6",
    base0D = "$color4",
    base0E = "$color5",
    base0F = "$color14",
  }
}
EOF
    echo "Generated neovim theme: $NVIM_THEME"
else
    echo "Warning: $COLORS_JSON not found, skipping neovim theme generation"
fi
